### ISSUE TITLE
Possible Bug in Query LLM Local 

### ISSUE THREAD

**Issue by sedetweiler** [chrish-slingshot/ComfyUI-ImageGlitcher#1]
I have tried this node with Jan.ai as well as oobabooga and both result in the same error.  Would love some guidance here.
I enabled API on both with the OpenAI formatting.

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\stable_diffusion\ComfyUI\ComfyUI\comfy_extras\nodes_clip_sdxl.py", line 42, in encode
    tokens = clip.tokenize(text_g)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\comfy\sd.py", line 122, in tokenize
    return self.tokenizer.tokenize_with_weights(text, return_word_ids)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\comfy\sdxl_clip.py", line 30, in tokenize_with_weights
    out["g"] = self.clip_g.tokenize_with_weights(text, return_word_ids)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 410, in tokenize_with_weights
    text = escape_important(text)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 249, in escape_important
    text = text.replace("\\)", "\0\1")
AttributeError: 'NoneType' object has no attribute 'replace'
```
![image](https://github.com/chrish-slingshot/CrasHUtils/assets/8366665/c18c760a-56d6-4e62-9fef-7e053ac5cf6c)

**Comment by chrish-slingshot** [comment]
Yeah I noticed the other day it wasn't working too. Thanks for reporting, I'll try and take a look and see what's going on.

**Comment by ShmuelRonen** [comment]
yes... Is not work with the new oobabooga API. Can you update the node?

**Comment by sedetweiler** [comment]
Any luck?  Would love to see this node work with a local LLM.

**Comment by sedetweiler** [comment]
Would love to feature this on my youtube, but it is currently broken.

**Comment by sedetweiler** [comment]
You planning on keeping these great tools alive?

**Comment by chrish-slingshot** [comment]
I do, sorry, had a lot on lately with work but I will try and take a look this week for you.

**Comment by GamingDaveUk** [comment]
> I do, sorry, had a lot on lately with work but I will try and take a look this week for you.

Can i nudge you on this chap?
I can get it to work on koboldcpp but alas not on Textgen webui, came looking for a solution as I cant use exl2 models in koboldcpp

**Comment by chrish-slingshot** [comment]
It's fixed! Hooray! Get latest and update the URL to the following and you should be good to go.

http://127.0.0.1:5000/v1/chat/completions

**Comment by chrish-slingshot** [comment]
Just pushed a couple of fixes too that allow you to change the system prompt.
